kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: kube-system
  name: r-admin-sa
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: rb-admin-sa
subjects:
- kind: ServiceAccount
  name: slug-autoscaler
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: r-admin-sa
  apiGroup: rbac.authorization.k8s.io