apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: nginx-2
  labels:
    app: nginx-2
spec:
  serviceName: "nginx-2"
  replicas: 5
  template:
    metadata:
      labels:
        app: nginx-2
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
        slug-autoscaler/autoscaler: "true"
        slug-autoscaler/autoscaler_percent_cpu: "50"
        slug-autoscaler/autoscaler_count: "0"
        slug-autoscaler/autoreduce_normal: "true"
        slug-autoscaler/autoreduce_percent_cpu: "10"
        slug-autoscaler/min_replicas: "3"
        slug-autoscaler/max_replicas: "8"
        slug-autoscaler/sts_owner_name: "nginx-2"
    spec:
      containers:
        - name: nginx-2
          image: nginx
          env:
            - name: POD_NS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: client
              containerPort: 80
          resources:
            limits:
              cpu: 150m
              memory: 300Mi
            requests:
              cpu: 75m
              memory: 150Mi
