apiVersion: v1
kind: ServiceAccount
metadata:
  name: slug-autoscaler
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: slug-autoscaler
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: slug-autoscaler
    spec:
      serviceAccountName: slug-autoscaler
      containers:
      - name: slug-autoscaler
        image: tedezed/slug-statefulset-autoscaler:2.0
        imagePullPolicy: Always
        env:
          - name: HEAPSTER
            value: http://heapster/api/v1/model
          - name: AUTOSCALER_COUNT
            value: "7"
          - name: TIME_QUERY
            value: "18"