apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: squirrel
  name: squirrel
  namespace: kube-system
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: squirrel
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: squirrel
    spec:
      containers:
      - command:
        - sleep
        - infinity
        image: tedezed/squirrel
        imagePullPolicy: Always
        name: squirrel
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: squirrel
      serviceAccountName: squirrel
