apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    cronjob.kubernetes.io/instantiate: manual
  labels:
    job-name: squirrel-rotation-now
  name: squirrel-rotation-now
  namespace: kube-system
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        job-name: squirrel-rotation-now
    spec:
      containers:
      - image: tedezed/squirrel:latest
        imagePullPolicy: Always
        name: squirrel
        env:
        - name: MODE
          value: rotation-secrets
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: squirrel
      serviceAccountName: squirrel
      terminationGracePeriodSeconds: 30
