apiVersion: v1
kind: ServiceAccount
metadata:
  name: slug-loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: slug-loadbalancer
    provider: slug-loadbalancer
  name: slug-loadbalancer
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: slug-loadbalancer
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: slug-loadbalancer
  labels:
    app: slug-loadbalancer
    version: v1
spec:
  replicas: 1
  selector:
    app: slug-loadbalancer
    version: v1
  template:
    metadata:
      labels:
        app: slug-loadbalancer
        version: v1
    spec:
      serviceAccountName: slug-loadbalancer
      containers:
      - name: slug-loadbalancer
        image: tedezed/slug-dynamic-loadbalancer:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        env:
          - name: TIME_QUERY
            value: "5"
          - name: TYPE_SET
            value: "rc"
          - name: NAME_SET
            value: "odoo-test"
          - name: TYPE_BALANCE
            value: "roundrobin"
          - name: COOKIE
            value: "true"