FROM debian:10
LABEL maintainer="juanmanuel.torres@aventurabinaria.es"

ENV KUSTOMIZE_VER="2.0.3" \
	KUBECTL_VER="1.18.18"

RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		ca-certificates \
		curl \
		wget \
		sudo \
		python-setuptools \
		python-yaml \
		gcc \
		make \
		build-essential \
		libssl-dev \
		libffi-dev \
		unicode \
		python-unicodecsv \
		g++ \
		python-dev \
		libtool \
		pkg-config \
		locales \
		nano \
		dnsutils \
		mariadb-client \
		postgresql-client \
		nmap \
		telnet \
		netcat \
		python3 \
		lsb-release \
		gnupg

RUN export GCSFUSE_REPO=gcsfuse-jessie \
    && echo "deb http://packages.cloud.google.com/apt $GCSFUSE_REPO main" | sudo tee /etc/apt/sources.list.d/gcsfuse.list \
    && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add - \
    && apt-get update \
    && apt-get install gcsfuse -y \
    && export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)" && \
    echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
    apt-get update -y && apt-get install google-cloud-sdk -y

RUN curl -o  /usr/bin/kubectl \
		-SL https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VER}/bin/linux/amd64/kubectl \
    && chmod +x  /usr/bin/kubectl

RUN curl -o /usr/bin/kustomize \
		-SL https://github.com/kubernetes-sigs/kustomize/releases/download/v${KUSTOMIZE_VER}/kustomize_${KUSTOMIZE_VER}_linux_amd64 \
    && chmod +x /usr/bin/kustomize

