apiVersion: v1
kind: Service
metadata:
  labels:
    app: slug-emailing
    provider: slug-emailing
  name: slug-emailing
  namespace: kube-system
spec:
  clusterIP: 10.35.247.34
  ports:
  - name: http
    port: 25
    protocol: TCP
  selector:
    app: slug-emailing
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: slug-emailing
    heritage: helm
  name: slug-emailing
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: slug-emailing
    spec:
      containers:
      - env:
        - name: HOSTNAME
          value: "mailjet-34tf4gert"
        - name: RELAYHOST
          value: "in.mailjet.com"
        - name: RELAYHOST_PORT
          value: "2525"
        - name: SMTP_KEY
          value: "ea1da0b3b3af3a516cd27c4df90e1f55"
        - name: SMTP_SECRET
          value: "97d4a1fd3b25add5b2f474cacb04cd5b"
        - name: NETWORKS
          value: "0.0.0.0/0"
        ports:
        - containerPort: 25
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 100m
        image: tedezed/emailing:latest
        name: slug-emailing
        securityContext:
          capabilities: {}
          privileged: true
apiVersion: v1
kind: Service
metadata:
  labels:
    app: slug-emailing
    provider: slug-emailing
  name: slug-emailing
  namespace: kube-system
spec:
  clusterIP: 10.0.10.100
  ports:
  - name: http
    port: 25
    protocol: TCP
  selector:
    app: slug-emailing
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: slug-emailing
  name: slug-emailing
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: slug-emailing
    spec:
      containers:
      - env:
        - name: HOSTNAME
          value: "emailing-rfger832nsdaf"
        - name: RELAYHOST
          value: "in.mailjet.com"
        - name: RELAYHOST_PORT
          value: "2525"
        - name: SMTP_KEY
          value: "asdasdasdasdasdasdasd"
        - name: SMTP_SECRET
          value: "asdqweasdqweasdqweasdqwe"
        - name: NETWORKS
          value: "0.0.0.0/0"
        ports:
        - containerPort: 25
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 100m
        image: tedezed/emailing:latest
        name: slug-emailing
        securityContext:
          capabilities: {}
          privileged: true
