apiVersion: v1
kind: Service
metadata:
  labels:
    app: secure-emailing
    provider: secure-emailing
  name: secure-emailing
  namespace: kube-system
spec:
  clusterIP: 10.0.10.100
  ports:
  - name: http
    port: 25
    protocol: TCP
  selector:
    app: secure-emailing
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: secure-emailing
  name: secure-emailing
  namespace: kube-system
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: secure-emailing
    spec:
      containers:
      - env:
        - name: REMOTE_HOST
          value: "slug-emailing"
        - name: REMOTE_PORT
          value: "25"
        - name: DB_HOST
          value: "postgres-emailing"
        - name: DB_NAME
          value: "emailing"
        - name: DB_USER
          value: "emailing"
        - name: PGPASSWORD
          value: "postgres"
        ports:
        - containerPort: 25
        image: tedezed/secure-emailing:latest
        name: secure-emailing
        securityContext:
          capabilities: {}
          privileged: true

