apiVersion: v1
kind: Namespace
metadata:
  name: apt-repository
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: apt-repository
    provider: apt-repository
  name: apt-repository
  namespace: apt-repository
spec:
  ports:
  - port: 80
  selector:
    app: apt-repository
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: apt-repository
    heritage: helm
  name: apt-repository
  namespace: apt-repository
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apt-repository
    spec:
      containers:
      - name: apt-repository
        image: tedezed/apt-repository:latest
        ports:
        - containerPort: 80
        env:
        - name: APT_DOMAIN
          value: "apt.example.com"
        - name: PGP_EMAIL
          value: "example@exmaple.com"
        - name: PGP_PASSWD
          value: "example_passwd_12345"
        - name: APT_DESCRIPTION
          value: "Example APT Repository"
        resources:
          limits:
            cpu: 850m
            memory: 1024Mi
          requests:
            cpu: 150m
            memory: 256Mi
        volumeMounts:
        - mountPath: /var/packages
          name: vol-apt-repository
          subPath: var-packages
        - mountPath: /usr/src/pagespeed
          name: vol-apt-repository
          subPath: usr-src-pagespeed
        - mountPath: /root/.gnupg
          name: vol-apt-repository
          subPath: root-gnupg
      volumes:
      - name: vol-apt-repository
        persistentVolumeClaim:
          claimName: apt-repository