#!/bin/bash

source /root/project_env

printenv > /backup-db-cron/backups/cronenv

echo "Mode: $MODE"
if [ $MODE = "databases" ] || [ $MODE = "all" ]; then
	echo "Submode: backup"
    /usr/bin/python3 /backup-db-cron/main.py mode=backup conf_mode=$CONF_MODE subtract_days=$DAYS_TO_DROP
fi
if [ $MODE = "snapshot" ] || [ $MODE = "all" ]; then
	echo "Submode: snapshot_label"
    /usr/bin/python3 /backup-db-cron/main.py mode=snapshot conf_mode=$CONF_MODE project=$PROJECT zone=$ZONE \
      subtract_days=$DAYS_TO_DROP_SNAPSHOT
fi