#!/bin/bash

source /root/project_env

printenv > /chronos/backups/cronenv

echo "Mode: $MODE"

if [ $MODE = "methodical_modules" ] || [ $MODE = "all" ]; then
    /usr/bin/python3 /chronos/main.py mode=backup conf_mode=$CONF_MODE subtract_days=$DAYS_TO_DROP
fi

if [ $MODE = "bare_modules" ] || [ $MODE = "all" ]; then
    /usr/bin/python3 /chronos/main.py mode=disks conf_mode=$CONF_MODE project=$PROJECT zone=$ZONE \
      subtract_days=$DAYS_TO_DROP_SNAPSHOT
fi