apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    nagios_check: "false"
  labels:
    app: liberty-elk-start
    pack: kube-system
  name: liberty-elk-start
  namespace: kube-system
spec:
  replicas: 1
  selector:
    app: liberty-elk-start
    k8s-app: liberty-elk-start
    pack: kube-system
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: liberty-elk-start
        k8s-app: liberty-elk-start
        pack: kube-system
    spec:
      serviceAccount: liberty-ingress
      serviceAccountName: liberty-ingress
      containers:
      - name: liberty
        image: tedezed/liberty-dynamic-ingress:latest
        imagePullPolicy: Always
        env:
        - name: TIME_QUERY
          value: "10"
        - name: ELK
          value: "true"
        - name: ELK_MODE
          value: "start"
        - name: ELK_HOST
          value: "elasticsearch-client.namespace.svc.cluster.local"
        - name: ELK_LIBERTY_NAMES
          value: "liberty1 liberty2"
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: liberty-elk-stop
  namespace: kube-system
spec:
  schedule: "00 00 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: liberty-elk-stop
            image: tedezed/liberty-dynamic-ingress:latest
            imagePullPolicy: Always
            env:
            - name: ELK
              value: "true"
            - name: ELK_MODE
              value: "stop"
            - name: ELK_HOST
              value: "elasticsearch-client.namespace.svc.cluster.local"
            - name: ELK_LIBERTY_NAMES
              value: "liberty1 liberty2"