apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    nagios_check: "false"
  labels:
    app: liberty-ingress-debug
    pack: kube-system
  name: liberty-ingress-debug
  namespace: kube-system
spec:
  replicas: 1
  selector:
    app: liberty-ingress-debug
    k8s-app: liberty-ingress-debug
    pack: kube-system
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: liberty-ingress-debug
        k8s-app: liberty-ingress-debug
        pack: kube-system
    spec:
      serviceAccount: liberty-ingress-2
      serviceAccountName: liberty-ingress-2
      containers:
      - name: liberty
        image: tedezed/liberty-dynamic-ingress:latest
        imagePullPolicy: Always
        env:
        - name: TIME_QUERY
          value: "25"
        - name: SECRET_USER
          value: debugtest
        - name: SECRET_PASSWD
          value: debugtest
        - name: NAME_LIBERTY
          value: liberty-ingress-2
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: liberty-logs
          mountPath: /var/log/nginx
          readOnly: false
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:6.3.1
        #command: ["sleep", "99999"]
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: liberty-logs
          mountPath: /var/log/nginx
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: filebeat-config
      - name: liberty-logs
        emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: kube-system
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: log
      paths:
        - /var/log/nginx/access.log
        - /var/log/nginx/custom_error.log
      input_type: log
      json.keys_under_root: true
      json.add_error_key: true
      json.message_key: log

    output.logstash:
      hosts: ["elastic-stack-logstash.elastic-stack.svc.cluster.local:5044"]