
build:
	docker build -f Dockerfile -t tedezed/pgbouncer:latest .

push:
	docker push tedezed/pgbouncer:latest

all:
	docker build -f Dockerfile -t tedezed/pgbouncer:latest .
	docker push tedezed/pgbouncer:latest
