apiVersion: v1
kind: ServiceAccount
metadata:
  name: slug-backup
  namespace: kube-system
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: slug-backup
  namespace: kube-system
  labels:
    app: slug-backup
spec:
  replicas: 1
  selector:
    name: slug-backup
  template:
    metadata:
      labels:
        name: slug-backup
    spec:
      serviceAccountName: slug-backup
      containers:
      - name: slug-backup
        image: tedezed/slug-backup-db-cron
        env:
        - name: DAYS_TO_DROP
          value: "15"
        - name: TIME
          value: "20 1 * * *"
        - name: DEV_MODE
          value: "0"
        volumeMounts:
        - mountPath: /slug-backup-db-cron/backups
          name: vol-slug-backup
          subPath: slug-backup
      volumes:
      - name: vol-slug-backup
        persistentVolumeClaim:
          claimName: pvc-slug-backup