apiVersion: v1
kind: Service
metadata:
  labels:
    app: slug-loadbalancer
    provider: slug-loadbalancer
  name: slug-loadbalancer
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
  selector:
    app: slug-loadbalancer
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: slug-loadbalancer
  labels:
    app: slug-loadbalancer
    version: v1
spec:
  replicas: 2
  selector:
    app: slug-loadbalancer
    version: v1
  template:
    metadata:
      labels:
        app: slug-loadbalancer
        version: v1
    spec:
      containers:
      - name: slug-loadbalancer
        image: tedezed/slug-statefulset-dynamic-loadbalancer
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        env:
          - name: KMASTER
            value: 10.0.0.1
          - name: TIME_QUERY
            value: "5"
          - name: CONF_KUBE_BASE64
            value: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
          - name: NAME_SET
            value: "odoo"
          - name: TYPE_BALANCE
            value: "roundrobin"