apiVersion: v1
kind: ReplicationController
metadata:
  name: slug-loadbalancer
  labels:
    app: slug-loadbalancer
    version: v1
spec:
  replicas: 1
  selector:
    app: slug-loadbalancer
    version: v1
  template:
    metadata:
      labels:
        app: slug-loadbalancer
        version: v1
    spec:
      volumes:
      - name: haproxy-secrets-volume
        secret:
          secretName: haproxy-secrets-volume
      containers:
      - image: quay.io/pulsecode/kubernetes-haproxy
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
        name: slug-loadbalancer
        ports:
        # All http services
        - containerPort: 80
          hostPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/haproxy/certs.d/
          name: haproxy-secrets-volume
        env:
          - name: SET_CONF
            value: "bob"