apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nutcrackers.tree.squirrel.local
spec:
  group: tree.squirrel.local
  version: v1
  scope: Namespaced
  names:
    plural: nutcrackers
    singular: nutcracker
    kind: Nutcrackers
    shortNames:
      - nc
