apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nuts.tree.squirrel.local
spec:
  group: tree.squirrel.local
  version: v1
  scope: Namespaced
  names:
    plural: nuts
    singular: nut
    kind: Nuts
    shortNames:
      - nut